#!/usr/bin/env bash

# Start with the simple dotfiles
mkdir -p ~/DotFilesBackup
dotfiles=( .bashrc .bash_aliases .hgrc .vim .vimrc .bash .gitignore_global .bash_autocomplete )
for i in "${dotfiles[@]}"
do
    if [ -e ~/$i ]; then
        mv ~/$i ~/DotFilesBackup/$i
    fi
done

source ~/
