#!/usr/bin/env bash

# Start with the simple dotfiles
dotfiles=( .bashrc .bash_aliases .hgrc .vim .vimrc .bash .gitignore_global )
for i in "${dotfiles[@]}"
do
    if [ -e ~/$i ]; then
        rm -rf ~/$i
    fi
done
